create table organizations (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    inn varchar(32),
    region varchar(255),
    description varchar(1000),
    created_at timestamp not null default current_timestamp
);

create table organization_members (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    full_name varchar(255) not null,
    email varchar(255),
    position varchar(255),
    role varchar(32) not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_members_organization foreign key (organization_id) references organizations (id) on delete cascade
);

create table logistics_records (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    shipment_number varchar(128) not null,
    route_from varchar(255) not null,
    route_to varchar(255) not null,
    shipped_at date not null,
    planned_delivery_date date not null,
    delivered_at date,
    status varchar(32) not null,
    responsible_department varchar(255),
    note varchar(1000),
    created_at timestamp not null default current_timestamp,
    constraint fk_records_organization foreign key (organization_id) references organizations (id) on delete cascade
);

create index idx_members_organization_id on organization_members(organization_id);
create index idx_records_organization_id on logistics_records(organization_id);
create index idx_records_status on logistics_records(status);
