create table if not exists system_admins (
    id bigint generated by default as identity primary key,
    login varchar(100) not null,
    password_hash varchar(255) not null,
    full_name varchar(255) not null,
    created_at timestamp not null default current_timestamp
);

create table if not exists auth_sessions (
    token varchar(128) primary key,
    role varchar(32) not null,
    organization_id bigint,
    login varchar(100) not null,
    full_name varchar(255) not null,
    created_at timestamp not null default current_timestamp
);

alter table organization_members add column if not exists login varchar(100);
alter table organization_members add column if not exists password_hash varchar(255);

update organization_members set login = 'owner1', password_hash = 'b410475f58265f6976b1fb350a2a48ceb387bf105f9c7e1215553dcd69a9270d' where id = 1;
update organization_members set login = 'employee1', password_hash = 'abfdba53a920fcae90050b862311816e51ee6cb623dfc31bfd8ba7e50b2686a4' where id = 2;
update organization_members set login = 'owner2', password_hash = 'b410475f58265f6976b1fb350a2a48ceb387bf105f9c7e1215553dcd69a9270d' where id = 3;
update organization_members set login = 'owner3', password_hash = 'efecf0e5f84e5028942a8111b514a9c6a96526c88bbecb0f53ec65f6a49a48ce' where id = 4;
update organization_members set login = 'employee2', password_hash = '7a4c204c858a1d861e55b215f9a5b84df3d6314feb4542f85394e1abf0e6b858' where id = 5;
update organization_members set login = 'owner4', password_hash = 'efecf0e5f84e5028942a8111b514a9c6a96526c88bbecb0f53ec65f6a49a48ce' where id = 6;
update organization_members set login = 'employee3', password_hash = 'abfdba53a920fcae90050b862311816e51ee6cb623dfc31bfd8ba7e50b2686a4' where id = 7;

alter table organization_members alter column login set not null;
alter table organization_members alter column password_hash set not null;

create unique index if not exists idx_system_admins_login on system_admins(login);
create unique index if not exists idx_members_login on organization_members(login);

insert into system_admins (id, login, password_hash, full_name)
select 1, 'admin', '893579fd9b1956136d9f1a544ce5b60a7754cb75691eabbe0c701c52d5442963', 'Системный администратор'
where not exists (
    select 1
    from system_admins
    where login = 'admin'
);
