create table if not exists organizations (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    inn varchar(32),
    region varchar(255),
    description varchar(1000),
    created_at timestamp not null default current_timestamp
);

create table if not exists organization_members (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    login varchar(100) not null,
    password_hash varchar(255) not null,
    full_name varchar(255) not null,
    email varchar(255),
    position varchar(255),
    role varchar(32) not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_members_organization foreign key (organization_id) references organizations (id) on delete cascade
);

create table if not exists logistics_records (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    shipment_number varchar(128) not null,
    route_from varchar(255) not null,
    route_to varchar(255) not null,
    shipped_at date not null,
    planned_delivery_date date not null,
    delivered_at date,
    status varchar(32) not null,
    responsible_department varchar(255),
    note varchar(1000),
    created_at timestamp not null default current_timestamp,
    constraint fk_records_organization foreign key (organization_id) references organizations (id) on delete cascade
);

create table if not exists system_admins (
    id bigint generated by default as identity primary key,
    login varchar(100) not null,
    password_hash varchar(255) not null,
    full_name varchar(255) not null,
    created_at timestamp not null default current_timestamp
);

create table if not exists auth_sessions (
    token varchar(128) primary key,
    role varchar(32) not null,
    organization_id bigint,
    login varchar(100) not null,
    full_name varchar(255) not null,
    created_at timestamp not null default current_timestamp
);

create index if not exists idx_members_organization_id on organization_members(organization_id);
create index if not exists idx_records_organization_id on logistics_records(organization_id);
create index if not exists idx_records_status on logistics_records(status);
create unique index if not exists idx_system_admins_login on system_admins(login);
create unique index if not exists idx_members_login on organization_members(login);

insert into system_admins (id, login, password_hash, full_name)
select 1, 'admin', '893579fd9b1956136d9f1a544ce5b60a7754cb75691eabbe0c701c52d5442963', 'Системный администратор'
where not exists (
    select 1 from system_admins where login = 'admin'
);

insert into organizations (id, name, inn, region, description)
select 1, 'АО «Почта России» - Центральный филиал', '7700000000', 'Москва', 'Демонстрационная организация для логистической отчетности'
where not exists (select 1 from organizations where id = 1);

insert into organizations (id, name, inn, region, description)
select 2, 'АО «Почта России» - Северный филиал', '7800000000', 'Санкт-Петербург', 'Организация для показа нескольких владельцев и сотрудников'
where not exists (select 1 from organizations where id = 2);

insert into organizations (id, name, inn, region, description)
select 3, 'АО «Почта России» - Приволжский филиал', '6300000000', 'Самара', 'Дополнительная организация для выборки и отчётов'
where not exists (select 1 from organizations where id = 3);

insert into organization_members (id, organization_id, login, password_hash, full_name, email, position, role)
select 1, 1, 'owner1', 'b410475f58265f6976b1fb350a2a48ceb387bf105f9c7e1215553dcd69a9270d', 'Иван Петров', 'ivan.petrov@mail.ru', 'Руководитель логистики', 'OWNER'
where not exists (select 1 from organization_members where id = 1);

insert into organization_members (id, organization_id, login, password_hash, full_name, email, position, role)
select 2, 1, 'employee1', 'abfdba53a920fcae90050b862311816e51ee6cb623dfc31bfd8ba7e50b2686a4', 'Анна Смирнова', 'anna.smirnova@mail.ru', 'Аналитик', 'EMPLOYEE'
where not exists (select 1 from organization_members where id = 2);

insert into organization_members (id, organization_id, login, password_hash, full_name, email, position, role)
select 3, 1, 'owner2', 'b410475f58265f6976b1fb350a2a48ceb387bf105f9c7e1215553dcd69a9270d', 'Мария Кузнецова', 'maria.kuznetsova@mail.ru', 'Старший специалист', 'OWNER'
where not exists (select 1 from organization_members where id = 3);

insert into organization_members (id, organization_id, login, password_hash, full_name, email, position, role)
select 4, 2, 'owner3', 'efecf0e5f84e5028942a8111b514a9c6a96526c88bbecb0f53ec65f6a49a48ce', 'Олег Иванов', 'oleg.ivanov@mail.ru', 'Руководитель филиала', 'OWNER'
where not exists (select 1 from organization_members where id = 4);

insert into organization_members (id, organization_id, login, password_hash, full_name, email, position, role)
select 5, 2, 'employee2', '7a4c204c858a1d861e55b215f9a5b84df3d6314feb4542f85394e1abf0e6b858', 'Елена Соколова', 'elena.sokolova@mail.ru', 'Логист', 'EMPLOYEE'
where not exists (select 1 from organization_members where id = 5);

insert into organization_members (id, organization_id, login, password_hash, full_name, email, position, role)
select 6, 3, 'owner4', 'efecf0e5f84e5028942a8111b514a9c6a96526c88bbecb0f53ec65f6a49a48ce', 'Дмитрий Орлов', 'dmitry.orlov@mail.ru', 'Владелец филиала', 'OWNER'
where not exists (select 1 from organization_members where id = 6);

insert into organization_members (id, organization_id, login, password_hash, full_name, email, position, role)
select 7, 3, 'employee3', 'abfdba53a920fcae90050b862311816e51ee6cb623dfc31bfd8ba7e50b2686a4', 'Татьяна Федорова', 'tatiana.fedorova@mail.ru', 'Сотрудник отдела отчетности', 'EMPLOYEE'
where not exists (select 1 from organization_members where id = 7);

insert into logistics_records (
    id, organization_id, shipment_number, route_from, route_to, shipped_at,
    planned_delivery_date, delivered_at, status, responsible_department, note
)
select 1, 1, 'RT-1001', 'Москва', 'Казань', current_date - 5, current_date - 2, current_date - 2, 'DELIVERED', 'Центральный сортировочный центр', 'Доставлено без отклонений'
where not exists (select 1 from logistics_records where id = 1);

insert into logistics_records (
    id, organization_id, shipment_number, route_from, route_to, shipped_at,
    planned_delivery_date, delivered_at, status, responsible_department, note
)
select 2, 1, 'RT-1002', 'Москва', 'Самара', current_date - 4, current_date - 1, current_date + 1, 'DELAYED', 'Центральный сортировочный центр', 'Есть риск нарушения срока'
where not exists (select 1 from logistics_records where id = 2);

insert into logistics_records (
    id, organization_id, shipment_number, route_from, route_to, shipped_at,
    planned_delivery_date, delivered_at, status, responsible_department, note
)
select 3, 1, 'RT-1003', 'Москва', 'Пермь', current_date - 3, current_date - 1, null, 'IN_TRANSIT', 'Центральный сортировочный центр', 'В пути'
where not exists (select 1 from logistics_records where id = 3);

insert into logistics_records (
    id, organization_id, shipment_number, route_from, route_to, shipped_at,
    planned_delivery_date, delivered_at, status, responsible_department, note
)
select 4, 2, 'RT-2001', 'Санкт-Петербург', 'Вологда', current_date - 2, current_date - 1, current_date - 1, 'DELIVERED', 'Северный логистический узел', 'Доставлено в срок'
where not exists (select 1 from logistics_records where id = 4);

insert into logistics_records (
    id, organization_id, shipment_number, route_from, route_to, shipped_at,
    planned_delivery_date, delivered_at, status, responsible_department, note
)
select 5, 2, 'RT-2002', 'Санкт-Петербург', 'Архангельск', current_date - 6, current_date - 3, current_date - 1, 'DELAYED', 'Северный логистический узел', 'Задержка из-за транспорта'
where not exists (select 1 from logistics_records where id = 5);

insert into logistics_records (
    id, organization_id, shipment_number, route_from, route_to, shipped_at,
    planned_delivery_date, delivered_at, status, responsible_department, note
)
select 6, 3, 'RT-3001', 'Самара', 'Уфа', current_date - 2, current_date - 1, current_date - 1, 'DELIVERED', 'Приволжский логистический центр', 'Завершено успешно'
where not exists (select 1 from logistics_records where id = 6);

insert into logistics_records (
    id, organization_id, shipment_number, route_from, route_to, shipped_at,
    planned_delivery_date, delivered_at, status, responsible_department, note
)
select 7, 3, 'RT-3002', 'Самара', 'Оренбург', current_date - 1, current_date + 1, null, 'IN_TRANSIT', 'Приволжский логистический центр', 'В обработке'
where not exists (select 1 from logistics_records where id = 7);

insert into logistics_records (
    id, organization_id, shipment_number, route_from, route_to, shipped_at,
    planned_delivery_date, delivered_at, status, responsible_department, note
)
select 8, 3, 'RT-3003', 'Самара', 'Саратов', current_date - 7, current_date - 4, current_date - 2, 'DELAYED', 'Приволжский логистический центр', 'Требует анализа'
where not exists (select 1 from logistics_records where id = 8);
