create table if not exists logistics_record_movements (
    id bigint generated by default as identity primary key,
    record_id bigint not null,
    movement_type varchar(64) not null,
    title varchar(255) not null,
    location varchar(255),
    event_date date not null,
    description varchar(1000),
    sort_order int not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_movements_record foreign key (record_id) references logistics_records (id) on delete cascade
);

create index if not exists idx_movements_record_id on logistics_record_movements(record_id);
create index if not exists idx_movements_record_order on logistics_record_movements(record_id, sort_order);

insert into logistics_record_movements (
    id, record_id, movement_type, title, location, event_date, description, sort_order
)
select 1, 1, 'CREATED', 'Создано отправление', 'Москва', current_date - 5, 'Отправление внесено в систему', 1
where not exists (select 1 from logistics_record_movements where id = 1);

insert into logistics_record_movements (
    id, record_id, movement_type, title, location, event_date, description, sort_order
)
select 2, 1, 'ACCEPTED', 'Принято на обработку', 'Центральный сортировочный центр', current_date - 4, 'Передано в логистический центр', 2
where not exists (select 1 from logistics_record_movements where id = 2);

insert into logistics_record_movements (
    id, record_id, movement_type, title, location, event_date, description, sort_order
)
select 3, 1, 'DELIVERED', 'Доставлено', 'Казань', current_date - 2, 'Получено адресатом', 3
where not exists (select 1 from logistics_record_movements where id = 3);

insert into logistics_record_movements (
    id, record_id, movement_type, title, location, event_date, description, sort_order
)
select 4, 2, 'CREATED', 'Создано отправление', 'Москва', current_date - 4, 'Отправление внесено в систему', 1
where not exists (select 1 from logistics_record_movements where id = 4);

insert into logistics_record_movements (
    id, record_id, movement_type, title, location, event_date, description, sort_order
)
select 5, 2, 'IN_TRANSIT', 'В пути', 'Самара', current_date - 1, 'Отправление находится в пути', 2
where not exists (select 1 from logistics_record_movements where id = 5);

insert into logistics_record_movements (
    id, record_id, movement_type, title, location, event_date, description, sort_order
)
select 6, 2, 'DELAYED', 'С задержкой', 'Самара', current_date + 1, 'Срок доставки нарушен', 3
where not exists (select 1 from logistics_record_movements where id = 6);

insert into logistics_record_movements (
    id, record_id, movement_type, title, location, event_date, description, sort_order
)
select 7, 3, 'CREATED', 'Создано отправление', 'Москва', current_date - 3, 'Отправление внесено в систему', 1
where not exists (select 1 from logistics_record_movements where id = 7);

insert into logistics_record_movements (
    id, record_id, movement_type, title, location, event_date, description, sort_order
)
select 8, 3, 'ACCEPTED', 'Принято на обработку', 'Центральный сортировочный центр', current_date - 2, 'Передано в логистический центр', 2
where not exists (select 1 from logistics_record_movements where id = 8);

insert into logistics_record_movements (
    id, record_id, movement_type, title, location, event_date, description, sort_order
)
select 9, 3, 'IN_TRANSIT', 'В пути', 'Пермь', current_date - 1, 'Отправление находится в пути', 3
where not exists (select 1 from logistics_record_movements where id = 9);

insert into logistics_record_movements (
    id, record_id, movement_type, title, location, event_date, description, sort_order
)
select 10, 6, 'CREATED', 'Создано отправление', 'Самара', current_date - 2, 'Отправление внесено в систему', 1
where not exists (select 1 from logistics_record_movements where id = 10);

insert into logistics_record_movements (
    id, record_id, movement_type, title, location, event_date, description, sort_order
)
select 11, 6, 'ACCEPTED', 'Принято на обработку', 'Приволжский логистический центр', current_date - 1, 'Передано в логистический центр', 2
where not exists (select 1 from logistics_record_movements where id = 11);

insert into logistics_record_movements (
    id, record_id, movement_type, title, location, event_date, description, sort_order
)
select 12, 6, 'DELIVERED', 'Доставлено', 'Уфа', current_date - 1, 'Получено адресатом', 3
where not exists (select 1 from logistics_record_movements where id = 12);
