alter table logistics_records
    add column if not exists deleted_at timestamp;

update logistics_records
set weight = 24.000
where id = 2;

update logistics_records
set deleted_at = current_timestamp
where id = 3;

create table if not exists logistics_action_history (
    id bigint generated by default as identity primary key,
    organization_id bigint not null,
    actor_login varchar(100) not null,
    actor_full_name varchar(255) not null,
    action_type varchar(32) not null,
    record_id bigint not null,
    record_shipment_number varchar(100) not null,
    summary text not null,
    before_state text,
    after_state text,
    reverted boolean not null default false,
    reverted_at timestamp,
    created_at timestamp not null default current_timestamp
);

create index if not exists idx_logistics_action_history_org_created on logistics_action_history (organization_id, created_at desc);
create index if not exists idx_logistics_action_history_org_actor_created on logistics_action_history (organization_id, actor_login, created_at desc);
create index if not exists idx_logistics_records_deleted_at on logistics_records (deleted_at);

insert into logistics_action_history (
    id, organization_id, actor_login, actor_full_name, action_type, record_id, record_shipment_number, summary, before_state, after_state, reverted, created_at
)
values
    (
        1,
        1,
        'owner1',
        'Иван Петров',
        'CREATED',
        1,
        'RT-1001',
        'Создал отправление RT-1001',
        null,
        '{"id":1,"organizationId":1,"shipmentNumber":"RT-1001","routeFrom":"Москва","routeTo":"Казань","shippedAt":"2026-05-10","plannedDeliveryDate":"2026-05-13","weight":1.0,"cost":250.0,"deliveredAt":"2026-05-13","status":"DELIVERED","responsibleDepartment":"Центральный сортировочный центр","note":"Доставлено без отклонений","deletedAt":null}',
        false,
        current_timestamp
    ),
    (
        2,
        1,
        'owner1',
        'Иван Петров',
        'UPDATED',
        2,
        'RT-1002',
        'Обновил отправление RT-1002, изменил вес с 10 кг на 24 кг',
        '{"id":2,"organizationId":1,"shipmentNumber":"RT-1002","routeFrom":"Москва","routeTo":"Самара","shippedAt":"2026-05-11","plannedDeliveryDate":"2026-05-14","weight":10.0,"cost":320.0,"deliveredAt":"2026-05-16","status":"DELAYED","responsibleDepartment":"Центральный сортировочный центр","note":"Есть риск нарушения срока","deletedAt":null}',
        '{"id":2,"organizationId":1,"shipmentNumber":"RT-1002","routeFrom":"Москва","routeTo":"Самара","shippedAt":"2026-05-11","plannedDeliveryDate":"2026-05-14","weight":24.0,"cost":320.0,"deliveredAt":"2026-05-16","status":"DELAYED","responsibleDepartment":"Центральный сортировочный центр","note":"Есть риск нарушения срока","deletedAt":null}',
        false,
        current_timestamp
    ),
    (
        3,
        1,
        'owner1',
        'Иван Петров',
        'DELETED',
        3,
        'RT-1003',
        'Удалил отправление RT-1003',
        '{"id":3,"organizationId":1,"shipmentNumber":"RT-1003","routeFrom":"Москва","routeTo":"Пермь","shippedAt":"2026-05-12","plannedDeliveryDate":"2026-05-14","weight":0.850,"cost":180.0,"deliveredAt":null,"status":"IN_TRANSIT","responsibleDepartment":"Центральный сортировочный центр","note":"В пути","deletedAt":null}',
        null,
        false,
        current_timestamp
    );

select setval(
    pg_get_serial_sequence('logistics_action_history', 'id'),
    (select coalesce(max(id), 1) from logistics_action_history),
    true
);
